import time
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver import ActionChains
driver = webdriver.Chrome()
driver.maximize_window()
driver.get("https://b2bcare-admin.ncell.axiata.com/")
driver.get_screenshot_as_file("abcdtest.png") #samedirectory

#wait = WebDriverWait(driver, 10)
time.sleep(5)
driver.find_element_by_id("LoginInput_UserNameOrEmailAddress").click()
driver.find_element_by_id("LoginInput_UserNameOrEmailAddress").send_keys("Euser1")
driver.find_element_by_id("LoginInput_Password").click()
driver.find_element_by_id("LoginInput_Password").send_keys("y!f3uujdZ%h7Pnkjkjm")
driver.find_element_by_xpath("/html/body/div/div/div/div/div/form/button").click()
print(driver.current_url)
print(driver.title)
#print(driver.page_source)
time.sleep(5)
#wait = WebDriverWait(driver, 5)
driver.find_element_by_css_selector("abp-layout-application.ng-tns-c89-0.ng-star-inserted div.container.ng-tns-c89-0 app-home.ng-star-inserted div.container.ng-star-inserted div.customer div.customer-title.mb-4 > a.btn.btn-primary.ng-star-inserted:nth-child(2)").click()
driver.find_element_by_id("companyName").click()
driver.find_element_by_id("companyName").send_keys("Amnill")
driver.find_element_by_id("companyAddress").click()
driver.find_element_by_id("companyAddress").send_keys("Jhamsikhel")
driver.find_element_by_id("panNo").click()
driver.find_element_by_id("panNo").send_keys("123456789")
driver.find_element_by_id("emailAddress").click()
driver.find_element_by_id("emailAddress").send_keys("prashant.test6@yopmail.com")
driver.find_element_by_id("managerEmailAddress").click()
driver.find_element_by_id("managerEmailAddress").send_keys("prashant.basnet@amniltech.com")
driver.find_element_by_id("password").click()
driver.find_element_by_id("password").send_keys("Amnil@1")
driver.find_element_by_id("lowBalanceThreshold").click()
driver.find_element_by_id("lowBalanceThreshold").send_keys("100")
driver.find_element_by_css_selector(".btn-primary").click()
time.sleep(10)
popup = driver.find_element_by_id("confirm")
actions = ActionChains(driver)
actions.move_to_element(popup).click()
#wait = WebDriverWait(driver,10) 
#wait.until(alertIsPresent())
#driver.switchTo().alert().accept();
alert = driver.switch_to_alert()
wait.until(alertIsPresent())
alert.accept()
time.sleep(5)
driver.find_element_by_partial_link_text("Manage API Credentia").click()
driver.find_element_by_id("msisdn").click()
driver.find_element_by_id("msisdn").send_keys("9860111435")
driver.find_element_by_id("channelID").click()
driver.find_element_by_id("channelID").send_keys("123")
driver.find_element_by_id("username").click()
driver.find_element_by_id("username").send_keys("EnterprisePortal")
driver.find_element_by_id("password").click()
driver.find_element_by_id("password").send_keys("N6jg%23trkp@E3L5u3")
driver.find_element_by_id("consumerKey").click()
driver.find_element_by_id("consumerKey").send_keys("pH8Nn5LFnd3gqIibTe7ZlOC9Zi4a")
driver.find_element_by_id("consumersecret").click()
driver.find_element_by_id("consumersecret").send_keys("4gUo5uh4FdlPI_Xym96N_sTkEWsa")
driver.find_element_by_id("consumerKeySandBox").click()
driver.find_element_by_id("consumerKeySandBox").send_keys("pH8Nn5LFnd3gqIibTe7ZlOC9Zi4a")
driver.find_element_by_id("consumersecretSandBox").click()
driver.find_element_by_id("consumersecretSandBox").send_keys("4gUo5uh4FdlPI_Xym96N_sTkEWsa")
driver.find_element_by_xpath("/html/body/app-root/abp-dynamic-layout/abp-layout-application/div/app-api-credentials/div/div/form/div/div[10]/button[2]").click()
time.sleep(10)
#ADD_Product
driver.find_elements_by_link_text("Product Management").click()
driver.find_elements_by_xpath("/html/body/app-root/abp-dynamic-layout/abp-layout-application/div/app-product-management/div/div/div[1]/a").click()
sel = Select (driver.find_element_by_id ("customer"))
sel.select_by_visible_text ('Prashant')
#sel.select_by_value ('Value')
#sel.select_by_index (1)
sel = Select (driver.find_element_by_id ("productCode"))
sel.select_by_visible_text ('S30263')

driver.find_element_by_id("name").click()
driver.find_element_by_id("name").send_keys("SMSProd")

sel = Select (driver.find_element_by_id ("productType"))
sel.select_by_visible_text ('Data')
driver.find_elements_by_xpath("/html[1]/body[1]/app-root[1]/abp-dynamic-layout[1]/abp-layout-application[1]/div[1]/app-assign-product[1]/div[1]/div[1]/div[2]/div[2]/div[2]/button[2]/span[1]").click()
time.sleep(10)
driver.find_elements_by_xpath("/html[1]/body[1]").click()
   # Add desired text/set input value
driver.find_element_by_id("dateFrom").click()
#driver.find_element_by_xpath("//div[text()='25']").click()
driver.find_element_by_xpath("/html/body/app-root/abp-dynamic-layout/abp-layout-application/div/app-activity-log/div/div/form/div/div[1]/div/div/ngb-datepicker/div[2]/div/ngb-datepicker-month/div[6]/div[4]/div").click()
#"//div[@class='btn-light ng-star-inserted']"
dates = driver.find_element_by_xpath("//div[@class='btn-light ng-star-inserted")
for date in dates:
    data = date.text
    print(date)
    if data == '25':
        break
#driver.find_element_by_id("dateFrom").send_keys("")
#driver.find_element_by_id("dateTo").click()
#driver.find_element_by_id("dateTp").send_keys("")

time.sleep(15)
driver.quit()